# Generated by Django 4.0.4 on 2022-05-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field_name',
            field=models.ImageField(default='default.jpg', upload_to=None),
        ),
    ]
