# Generated by Django 4.0.4 on 2022-05-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='field_name',
            new_name='img',
        ),
    ]
