# Generated by Django 3.1.5 on 2022-06-11 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_auto_20220611_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='followings',
        ),
        migrations.AddField(
            model_name='following',
            name='followings',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
